### ISSUE TITLE
rclone can't find rclone.conf

### ISSUE THREAD

**Issue by guillaumelachaud** [tynor88/docker-rclone#12]
The docker image is using /config/rclone.conf whereas rclone is looking for a file at /root/.config/rclone/rclone.conf.

`Config file "/root/.config/rclone/rclone.conf" not found - using defaults`

**Comment by erwinkloosterboer** [comment]
Probably because you were logged in as root instead of the user 'abc' which uses the /config/.rclone.conf file. `docker exec -ti -u abc rclone /bin/ash -c "rclone config"` should give you the config mounted in /config
