### ISSUE TITLE
Push new build to dockerhub

### ISSUE THREAD

**Issue by janajri** [tynor88/docker-rclone#5]
Thanks for this docker image, really useful but would you mind pushing latest build? I'd like to use latest features in 1.39

**Comment by efrecon** [comment]
Still no build? Support for box is missing from the current build (1.35 of rclone, which is, at the time of writing 1.40). Can I help in any way?

**Comment by efrecon** [comment]
I have sent you a [PR](https://github.com/tynor88/docker-rclone/pull/6) that entirely automates the process of creating tags for every known version of rclone. Resulting images are as exemplified [here](https://hub.docker.com/r/efrecon/rclone/tags/).

**Comment by tynor88** [comment]
Hi @efrecon  thanks for the PR. It's a great idea. 

I will merge it today.

**Comment by tynor88** [comment]
Merged. 1.40 is up @janajri and @efrecon https://hub.docker.com/r/tynor88/rclone/tags/

Thanks for the PR!

**Comment by Skaronator** [comment]
The latest tag didn't get a update?

**Comment by efrecon** [comment]
No, latest doesn't appear as an official tag at the rclone project. I guess latest should be based on "current", which is at another URL, the hooks builds needs to manually modified. An alternative would be to have two different Dockerfiles, both used at the hub: one for building all existing releases in one go, another one for building "current" (which would translate to latest).

**Comment by Skaronator** [comment]
Could you not use the highest number as `latest` tag? Or select the first element from the github json file?

**Comment by tynor88** [comment]
@Skaronator 👍 good idea, sounds like an easy fix.

I can also ask the maintainer of rclone, if he can add a commit-hook to his repo, to force a new build of this docker image.

**Comment by efrecon** [comment]
@Skaronator @tynor88 I am working on a fix using the top release number of the list and considering it as latest. Hope to send a new PR for this soon.

**Comment by Skaronator** [comment]
Cool, thanks!

**Comment by efrecon** [comment]
Request is at #8. Hope you can merge it. It works as advertised on my version of this at the [hub](https://hub.docker.com/r/efrecon/rclone/tags/).

**Comment by tynor88** [comment]
@Skaronator @efrecon merged. Thanks for the PR 👍
