### ISSUE TITLE
Is there a way to change the user/group that it runs as?

### ISSUE THREAD

**Issue by 1n5aN1aC** [tynor88/docker-rclone#9]
As title.  It would be very helpful to have an environment variable to set the PUID or PGID for the backup process to run as.

Is there any functionality for this?  Thanks!

**Comment by tynor88** [comment]
Sure. See https://github.com/tynor88/docker-rclone/blob/dev/root/etc/cont-init.d/10-adduser

Use environment variables PUID and GUID
